---
#
# .github/workflows/tests.yml
#
name: Tests Workflow
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - develop
    tags:
      - "*.*.*"
  pull_request:

env:
  REVIEWDOG_GITHUB_API_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: "sparse"

defaults:
  run:
    shell: bash

jobs:
  tests:
    name: Run Tests
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Check Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@main
        with:
          fail-mode: true
      - name: Test install.sh script
        run: nix develop .#ci-test --command ./install.sh
