---
#
# .github/workflows/tests.yml
#
# https://github.com/actions-rust-lang/setup-rust-toolchain
#
name: Tests Workflow
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - develop
  pull_request:

env:
  REVIEWDOG_GITHUB_API_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: "sparse"

defaults:
  run:
    shell: bash

jobs:
  tests:
    name: Run Tests
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          cache: true
      - name: Check Rust Version
        run: rustc --version
      - name: Test install.sh script
        run: |-
          ./install.sh
